#!/usr/bin/env python
import re

mailto = "andrei@ceata.org"
user = "www-data"
location = "/var/www/alaveteli"

template = open("config/crontab.ugly").read()
template = re.sub(r"MAILTO=.*", "MAILTO=%s" % mailto, template)
template = template.replace("!!(*= $user *)!!", user)
template = re.sub(r"/data/vhost/.*/script", location + "/script", template)

print template



